"""rename address

Revision ID: 73520c192188
Revises: 80597db6d029
Create Date: 2024-01-08 15:52:40.901861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73520c192188'
down_revision = '80597db6d029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
